// <auto-generated />
using System;
using System.Collections.Generic;
using CentralAntifraude.Infrastructure.Persistencia;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CentralAntifraude.Infrastructure.Persistencia.Migrations
{
    [DbContext(typeof(CentralAntifraudeDbContext))]
    [Migration("20260904004807_IntegracoesEIngestao")]
    partial class IntegracoesEIngestao
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CentralAntifraude.Domain.Auditoria.RegistroDeAuditoria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AutorDescricao")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("autor_descricao");

                    b.Property<Guid?>("AutorId")
                        .HasColumnType("uuid")
                        .HasColumnName("autor_id");

                    b.Property<string>("Detalhe")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("detalhe");

                    b.Property<string>("Entidade")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("entidade");

                    b.Property<string>("EntidadeId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("entidade_id");

                    b.Property<string>("IdDeCorrelacao")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("id_de_correlacao");

                    b.Property<DateTimeOffset>("OcorridoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ocorrido_em");

                    b.Property<string>("Operacao")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("operacao");

                    b.Property<Guid>("OrganizacaoId")
                        .HasColumnType("uuid")
                        .HasColumnName("organizacao_id");

                    b.HasKey("Id")
                        .HasName("pk_registros_de_auditoria");

                    b.HasIndex("OrganizacaoId", "OcorridoEm")
                        .HasDatabaseName("ix_registros_de_auditoria_organizacao_id_ocorrido_em");

                    b.ToTable("registros_de_auditoria", (string)null);
                });

            modelBuilder.Entity("CentralAntifraude.Domain.Identidade.Organizacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativa")
                        .HasColumnType("boolean")
                        .HasColumnName("ativa");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("codigo");

                    b.Property<DateTimeOffset>("CriadaEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criada_em");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome");

                    b.HasKey("Id")
                        .HasName("pk_organizacoes");

                    b.HasIndex("Codigo")
                        .IsUnique()
                        .HasDatabaseName("ix_organizacoes_codigo");

                    b.ToTable("organizacoes", (string)null);
                });

            modelBuilder.Entity("CentralAntifraude.Domain.Identidade.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<DateTimeOffset>("ExpiraEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expira_em");

                    b.Property<Guid>("FamiliaId")
                        .HasColumnType("uuid")
                        .HasColumnName("familia_id");

                    b.Property<string>("HashDoToken")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("hash_do_token");

                    b.Property<string>("MotivoDaRevogacao")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("motivo_da_revogacao");

                    b.Property<Guid>("OrganizacaoId")
                        .HasColumnType("uuid")
                        .HasColumnName("organizacao_id");

                    b.Property<DateTimeOffset?>("RevogadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revogado_em");

                    b.Property<DateTimeOffset?>("UsadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("usado_em");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id")
                        .HasName("pk_refresh_tokens");

                    b.HasIndex("FamiliaId")
                        .HasDatabaseName("ix_refresh_tokens_familia_id");

                    b.HasIndex("HashDoToken")
                        .IsUnique()
                        .HasDatabaseName("ix_refresh_tokens_hash_do_token");

                    b.HasIndex("UsuarioId")
                        .HasDatabaseName("ix_refresh_tokens_usuario_id");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("CentralAntifraude.Domain.Identidade.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<DateTimeOffset>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("email");

                    b.Property<string>("HashDaSenha")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("hash_da_senha");

                    b.Property<string>("NomeCompleto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome_completo");

                    b.Property<Guid>("OrganizacaoId")
                        .HasColumnType("uuid")
                        .HasColumnName("organizacao_id");

                    b.Property<string>("Perfil")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("perfil");

                    b.HasKey("Id")
                        .HasName("pk_usuarios");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_usuarios_email");

                    b.HasIndex("OrganizacaoId", "NomeCompleto")
                        .HasDatabaseName("ix_usuarios_organizacao_id_nome_completo");

                    b.ToTable("usuarios", (string)null);
                });

            modelBuilder.Entity("CentralAntifraude.Domain.Integracoes.CredencialDeIntegracao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CriadaEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criada_em");

                    b.Property<string>("HashDoSegredo")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("hash_do_segredo");

                    b.Property<string>("IdentificadorPublico")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("identificador_publico");

                    b.Property<Guid>("IntegracaoId")
                        .HasColumnType("uuid")
                        .HasColumnName("integracao_id");

                    b.Property<string>("MotivoDaRevogacao")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("motivo_da_revogacao");

                    b.Property<Guid>("OrganizacaoId")
                        .HasColumnType("uuid")
                        .HasColumnName("organizacao_id");

                    b.Property<DateTimeOffset?>("RevogadaEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revogada_em");

                    b.Property<DateTimeOffset?>("UsadaPelaUltimaVezEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("usada_pela_ultima_vez_em");

                    b.HasKey("Id")
                        .HasName("pk_credenciais_de_integracao");

                    b.HasIndex("IdentificadorPublico")
                        .IsUnique()
                        .HasDatabaseName("ix_credenciais_de_integracao_identificador_publico");

                    b.HasIndex("IntegracaoId")
                        .HasDatabaseName("ix_credenciais_de_integracao_integracao_id");

                    b.ToTable("credenciais_de_integracao", (string)null);
                });

            modelBuilder.Entity("CentralAntifraude.Domain.Integracoes.Integracao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativa")
                        .HasColumnType("boolean")
                        .HasColumnName("ativa");

                    b.Property<DateTimeOffset>("AtualizadaEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizada_em");

                    b.Property<DateTimeOffset>("CriadaEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criada_em");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("nome");

                    b.Property<Guid>("OrganizacaoId")
                        .HasColumnType("uuid")
                        .HasColumnName("organizacao_id");

                    b.HasKey("Id")
                        .HasName("pk_integracoes");

                    b.HasIndex("OrganizacaoId", "Nome")
                        .HasDatabaseName("ix_integracoes_organizacao_id_nome");

                    b.ToTable("integracoes", (string)null);
                });

            modelBuilder.Entity("CentralAntifraude.Domain.Transacoes.Transacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ChaveDeIdempotencia")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("chave_de_idempotencia");

                    b.Property<string>("ClienteExternoId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("cliente_externo_id");

                    b.Property<string>("FingerprintDoDispositivo")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("fingerprint_do_dispositivo");

                    b.Property<string>("FingerprintDoIp")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("fingerprint_do_ip");

                    b.Property<string>("FingerprintDoPayload")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("fingerprint_do_payload");

                    b.Property<string>("IdentificadorExterno")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("identificador_externo");

                    b.Property<Guid>("IntegracaoId")
                        .HasColumnType("uuid")
                        .HasColumnName("integracao_id");

                    b.Property<DateTimeOffset>("OcorridaEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ocorrida_em");

                    b.Property<Guid>("OrganizacaoId")
                        .HasColumnType("uuid")
                        .HasColumnName("organizacao_id");

                    b.Property<string>("PaisDeOrigem")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("pais_de_origem");

                    b.Property<DateTimeOffset>("RecebidaEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recebida_em");

                    b.Property<string>("ReferenciaDoInstrumento")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("referencia_do_instrumento");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Valor", "CentralAntifraude.Domain.Transacoes.Transacao.Valor#Dinheiro", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Moeda")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("moeda");

                            b1.Property<decimal>("Valor")
                                .HasPrecision(18, 4)
                                .HasColumnType("numeric(18,4)")
                                .HasColumnName("valor");
                        });

                    b.HasKey("Id")
                        .HasName("pk_transacoes");

                    b.HasIndex("IntegracaoId")
                        .HasDatabaseName("ix_transacoes_integracao_id");

                    b.HasIndex("OrganizacaoId", "RecebidaEm")
                        .HasDatabaseName("ix_transacoes_organizacao_id_recebida_em");

                    b.HasIndex("OrganizacaoId", "ClienteExternoId", "OcorridaEm")
                        .HasDatabaseName("ix_transacoes_organizacao_id_cliente_externo_id_ocorrida_em");

                    b.HasIndex("OrganizacaoId", "IntegracaoId", "ChaveDeIdempotencia")
                        .IsUnique()
                        .HasDatabaseName("ix_transacoes_idempotencia");

                    b.HasIndex("OrganizacaoId", "IntegracaoId", "IdentificadorExterno")
                        .IsUnique()
                        .HasDatabaseName("ix_transacoes_identificador_externo");

                    b.ToTable("transacoes", (string)null);
                });

            modelBuilder.Entity("CentralAntifraude.Domain.Identidade.RefreshToken", b =>
                {
                    b.HasOne("CentralAntifraude.Domain.Identidade.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_refresh_tokens_usuarios_usuario_id");
                });

            modelBuilder.Entity("CentralAntifraude.Domain.Identidade.Usuario", b =>
                {
                    b.HasOne("CentralAntifraude.Domain.Identidade.Organizacao", null)
                        .WithMany()
                        .HasForeignKey("OrganizacaoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_usuarios_organizacoes_organizacao_id");
                });

            modelBuilder.Entity("CentralAntifraude.Domain.Integracoes.CredencialDeIntegracao", b =>
                {
                    b.HasOne("CentralAntifraude.Domain.Integracoes.Integracao", null)
                        .WithMany()
                        .HasForeignKey("IntegracaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_credenciais_de_integracao_integracoes_integracao_id");
                });

            modelBuilder.Entity("CentralAntifraude.Domain.Integracoes.Integracao", b =>
                {
                    b.HasOne("CentralAntifraude.Domain.Identidade.Organizacao", null)
                        .WithMany()
                        .HasForeignKey("OrganizacaoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_integracoes_organizacoes_organizacao_id");
                });

            modelBuilder.Entity("CentralAntifraude.Domain.Transacoes.Transacao", b =>
                {
                    b.HasOne("CentralAntifraude.Domain.Integracoes.Integracao", null)
                        .WithMany()
                        .HasForeignKey("IntegracaoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_transacoes_integracoes_integracao_id");
                });
#pragma warning restore 612, 618
        }
    }
}
