// <auto-generated />
using System;
using System.Collections.Generic;
using CentralAntifraude.Infrastructure.Persistencia;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CentralAntifraude.Infrastructure.Persistencia.Migrations
{
    [DbContext(typeof(CentralAntifraudeDbContext))]
    [Migration("20260905024012_AlertasOperacionais")]
    partial class AlertasOperacionais
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CentralAntifraude.Domain.Alertas.Alerta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AvaliacaoId")
                        .HasColumnType("uuid")
                        .HasColumnName("avaliacao_id");

                    b.Property<DateTimeOffset>("AvaliadaEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("avaliada_em");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("Decisao")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("decisao");

                    b.Property<Guid>("EventoId")
                        .HasColumnType("uuid")
                        .HasColumnName("evento_id");

                    b.Property<string>("IdDeCorrelacao")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("id_de_correlacao");

                    b.Property<Guid>("OrganizacaoId")
                        .HasColumnType("uuid")
                        .HasColumnName("organizacao_id");

                    b.Property<string>("Prioridade")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("prioridade");

                    b.Property<int>("Score")
                        .HasColumnType("integer")
                        .HasColumnName("score");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<Guid>("TransacaoId")
                        .HasColumnType("uuid")
                        .HasColumnName("transacao_id");

                    b.Property<int>("VersaoDaPolitica")
                        .HasColumnType("integer")
                        .HasColumnName("versao_da_politica");

                    b.HasKey("Id")
                        .HasName("pk_alertas");

                    b.HasIndex("AvaliacaoId")
                        .IsUnique()
                        .HasDatabaseName("ix_alertas_avaliacao");

                    b.HasIndex("TransacaoId")
                        .HasDatabaseName("ix_alertas_transacao_id");

                    b.HasIndex("OrganizacaoId", "Status", "CriadoEm")
                        .HasDatabaseName("ix_alertas_organizacao_status_criado");

                    b.ToTable("alertas", (string)null);
                });

            modelBuilder.Entity("CentralAntifraude.Domain.Auditoria.RegistroDeAuditoria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AutorDescricao")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("autor_descricao");

                    b.Property<Guid?>("AutorId")
                        .HasColumnType("uuid")
                        .HasColumnName("autor_id");

                    b.Property<string>("Detalhe")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("detalhe");

                    b.Property<string>("Entidade")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("entidade");

                    b.Property<string>("EntidadeId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("entidade_id");

                    b.Property<string>("IdDeCorrelacao")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("id_de_correlacao");

                    b.Property<DateTimeOffset>("OcorridoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ocorrido_em");

                    b.Property<string>("Operacao")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("operacao");

                    b.Property<Guid>("OrganizacaoId")
                        .HasColumnType("uuid")
                        .HasColumnName("organizacao_id");

                    b.HasKey("Id")
                        .HasName("pk_registros_de_auditoria");

                    b.HasIndex("OrganizacaoId", "OcorridoEm")
                        .HasDatabaseName("ix_registros_de_auditoria_organizacao_id_ocorrido_em");

                    b.ToTable("registros_de_auditoria", (string)null);
                });

            modelBuilder.Entity("CentralAntifraude.Domain.Eventos.EventoDeSaida", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Conteudo")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("conteudo");

                    b.Property<string>("IdDeCorrelacao")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("id_de_correlacao");

                    b.Property<DateTimeOffset>("OcorridoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ocorrido_em");

                    b.Property<Guid>("OrganizacaoId")
                        .HasColumnType("uuid")
                        .HasColumnName("organizacao_id");

                    b.Property<DateTimeOffset?>("PublicadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("publicado_em");

                    b.Property<int>("TentativasDePublicacao")
                        .HasColumnType("integer")
                        .HasColumnName("tentativas_de_publicacao");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("tipo");

                    b.HasKey("Id")
                        .HasName("pk_eventos_de_saida");

                    b.HasIndex("OrganizacaoId")
                        .HasDatabaseName("ix_eventos_de_saida_organizacao_id");

                    b.HasIndex("PublicadoEm", "OcorridoEm")
                        .HasDatabaseName("ix_eventos_de_saida_pendentes")
                        .HasFilter("publicado_em IS NULL");

                    b.ToTable("eventos_de_saida", (string)null);
                });

            modelBuilder.Entity("CentralAntifraude.Domain.Eventos.EventoProcessado", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Consumidor")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("consumidor");

                    b.Property<Guid>("EventoId")
                        .HasColumnType("uuid")
                        .HasColumnName("evento_id");

                    b.Property<string>("IdDeCorrelacao")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("id_de_correlacao");

                    b.Property<Guid>("OrganizacaoId")
                        .HasColumnType("uuid")
                        .HasColumnName("organizacao_id");

                    b.Property<DateTimeOffset>("ProcessadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processado_em");

                    b.Property<string>("TipoDoEvento")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("tipo_do_evento");

                    b.HasKey("Id")
                        .HasName("pk_eventos_processados");

                    b.HasIndex("OrganizacaoId")
                        .HasDatabaseName("ix_eventos_processados_organizacao_id");

                    b.HasIndex("Consumidor", "EventoId")
                        .IsUnique()
                        .HasDatabaseName("ix_eventos_processados_consumidor_evento");

                    b.ToTable("eventos_processados", (string)null);
                });

            modelBuilder.Entity("CentralAntifraude.Domain.Identidade.Organizacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativa")
                        .HasColumnType("boolean")
                        .HasColumnName("ativa");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("codigo");

                    b.Property<DateTimeOffset>("CriadaEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criada_em");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome");

                    b.HasKey("Id")
                        .HasName("pk_organizacoes");

                    b.HasIndex("Codigo")
                        .IsUnique()
                        .HasDatabaseName("ix_organizacoes_codigo");

                    b.ToTable("organizacoes", (string)null);
                });

            modelBuilder.Entity("CentralAntifraude.Domain.Identidade.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<DateTimeOffset>("ExpiraEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expira_em");

                    b.Property<Guid>("FamiliaId")
                        .HasColumnType("uuid")
                        .HasColumnName("familia_id");

                    b.Property<string>("HashDoToken")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("hash_do_token");

                    b.Property<string>("MotivoDaRevogacao")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("motivo_da_revogacao");

                    b.Property<Guid>("OrganizacaoId")
                        .HasColumnType("uuid")
                        .HasColumnName("organizacao_id");

                    b.Property<DateTimeOffset?>("RevogadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revogado_em");

                    b.Property<DateTimeOffset?>("UsadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("usado_em");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id")
                        .HasName("pk_refresh_tokens");

                    b.HasIndex("FamiliaId")
                        .HasDatabaseName("ix_refresh_tokens_familia_id");

                    b.HasIndex("HashDoToken")
                        .IsUnique()
                        .HasDatabaseName("ix_refresh_tokens_hash_do_token");

                    b.HasIndex("UsuarioId")
                        .HasDatabaseName("ix_refresh_tokens_usuario_id");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("CentralAntifraude.Domain.Identidade.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<DateTimeOffset>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("email");

                    b.Property<string>("HashDaSenha")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("hash_da_senha");

                    b.Property<string>("NomeCompleto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome_completo");

                    b.Property<Guid>("OrganizacaoId")
                        .HasColumnType("uuid")
                        .HasColumnName("organizacao_id");

                    b.Property<string>("Perfil")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("perfil");

                    b.HasKey("Id")
                        .HasName("pk_usuarios");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_usuarios_email");

                    b.HasIndex("OrganizacaoId", "NomeCompleto")
                        .HasDatabaseName("ix_usuarios_organizacao_id_nome_completo");

                    b.ToTable("usuarios", (string)null);
                });

            modelBuilder.Entity("CentralAntifraude.Domain.Integracoes.CredencialDeIntegracao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CriadaEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criada_em");

                    b.Property<string>("HashDoSegredo")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("hash_do_segredo");

                    b.Property<string>("IdentificadorPublico")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("identificador_publico");

                    b.Property<Guid>("IntegracaoId")
                        .HasColumnType("uuid")
                        .HasColumnName("integracao_id");

                    b.Property<string>("MotivoDaRevogacao")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("motivo_da_revogacao");

                    b.Property<Guid>("OrganizacaoId")
                        .HasColumnType("uuid")
                        .HasColumnName("organizacao_id");

                    b.Property<DateTimeOffset?>("RevogadaEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revogada_em");

                    b.Property<DateTimeOffset?>("UsadaPelaUltimaVezEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("usada_pela_ultima_vez_em");

                    b.HasKey("Id")
                        .HasName("pk_credenciais_de_integracao");

                    b.HasIndex("IdentificadorPublico")
                        .IsUnique()
                        .HasDatabaseName("ix_credenciais_de_integracao_identificador_publico");

                    b.HasIndex("IntegracaoId")
                        .HasDatabaseName("ix_credenciais_de_integracao_integracao_id");

                    b.ToTable("credenciais_de_integracao", (string)null);
                });

            modelBuilder.Entity("CentralAntifraude.Domain.Integracoes.Integracao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativa")
                        .HasColumnType("boolean")
                        .HasColumnName("ativa");

                    b.Property<DateTimeOffset>("AtualizadaEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizada_em");

                    b.Property<DateTimeOffset>("CriadaEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criada_em");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("nome");

                    b.Property<Guid>("OrganizacaoId")
                        .HasColumnType("uuid")
                        .HasColumnName("organizacao_id");

                    b.HasKey("Id")
                        .HasName("pk_integracoes");

                    b.HasIndex("OrganizacaoId", "Nome")
                        .HasDatabaseName("ix_integracoes_organizacao_id_nome");

                    b.ToTable("integracoes", (string)null);
                });

            modelBuilder.Entity("CentralAntifraude.Domain.Operacao.ResumoDiarioDeDecisoes", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<string>("Decisao")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("decisao");

                    b.Property<DateOnly>("Dia")
                        .HasColumnType("date")
                        .HasColumnName("dia");

                    b.Property<Guid>("OrganizacaoId")
                        .HasColumnType("uuid")
                        .HasColumnName("organizacao_id");

                    b.Property<int>("Quantidade")
                        .HasColumnType("integer")
                        .HasColumnName("quantidade");

                    b.HasKey("Id")
                        .HasName("pk_resumo_diario_de_decisoes");

                    b.HasIndex("OrganizacaoId", "Dia", "Decisao")
                        .IsUnique()
                        .HasDatabaseName("ix_resumo_diario_organizacao_dia_decisao");

                    b.ToTable("resumo_diario_de_decisoes", (string)null);
                });

            modelBuilder.Entity("CentralAntifraude.Domain.Risco.AvaliacaoDeRisco", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("AvaliadaEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("avaliada_em");

                    b.Property<string>("Decisao")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("decisao");

                    b.Property<int>("NumeroDaVersaoDePerfil")
                        .HasColumnType("integer")
                        .HasColumnName("numero_da_versao_de_perfil");

                    b.Property<Guid>("OrganizacaoId")
                        .HasColumnType("uuid")
                        .HasColumnName("organizacao_id");

                    b.Property<int>("Score")
                        .HasColumnType("integer")
                        .HasColumnName("score");

                    b.Property<Guid>("TransacaoId")
                        .HasColumnType("uuid")
                        .HasColumnName("transacao_id");

                    b.Property<Guid>("VersaoDePerfilId")
                        .HasColumnType("uuid")
                        .HasColumnName("versao_de_perfil_id");

                    b.Property<string>("VersaoDoMotorUsada")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("versao_do_motor_usada");

                    b.HasKey("Id")
                        .HasName("pk_avaliacoes_de_risco");

                    b.HasIndex("TransacaoId")
                        .IsUnique()
                        .HasDatabaseName("ix_avaliacoes_de_risco_transacao");

                    b.HasIndex("VersaoDePerfilId")
                        .HasDatabaseName("ix_avaliacoes_de_risco_versao_de_perfil_id");

                    b.HasIndex("OrganizacaoId", "Decisao", "AvaliadaEm")
                        .HasDatabaseName("ix_avaliacoes_de_risco_organizacao_id_decisao_avaliada_em");

                    b.ToTable("avaliacoes_de_risco", (string)null);
                });

            modelBuilder.Entity("CentralAntifraude.Domain.Risco.PerfilDeRisco", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("nome");

                    b.Property<Guid>("OrganizacaoId")
                        .HasColumnType("uuid")
                        .HasColumnName("organizacao_id");

                    b.HasKey("Id")
                        .HasName("pk_perfis_de_risco");

                    b.HasIndex("OrganizacaoId")
                        .HasDatabaseName("ix_perfis_de_risco_organizacao_id");

                    b.ToTable("perfis_de_risco", (string)null);
                });

            modelBuilder.Entity("CentralAntifraude.Domain.Risco.Regra", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CriadaEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criada_em");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("nome");

                    b.Property<Guid>("OrganizacaoId")
                        .HasColumnType("uuid")
                        .HasColumnName("organizacao_id");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("tipo");

                    b.HasKey("Id")
                        .HasName("pk_regras");

                    b.HasIndex("OrganizacaoId", "Tipo")
                        .IsUnique()
                        .HasDatabaseName("ix_regras_organizacao_id_tipo");

                    b.ToTable("regras", (string)null);
                });

            modelBuilder.Entity("CentralAntifraude.Domain.Risco.SinalDeRisco", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AvaliacaoId")
                        .HasColumnType("uuid")
                        .HasColumnName("avaliacao_id");

                    b.Property<string>("DadosDaEvidencia")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("dados_da_evidencia");

                    b.Property<string>("Explicacao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("explicacao");

                    b.Property<int>("NumeroDaVersaoDeRegra")
                        .HasColumnType("integer")
                        .HasColumnName("numero_da_versao_de_regra");

                    b.Property<Guid>("OrganizacaoId")
                        .HasColumnType("uuid")
                        .HasColumnName("organizacao_id");

                    b.Property<int>("Pontos")
                        .HasColumnType("integer")
                        .HasColumnName("pontos");

                    b.Property<Guid>("RegraId")
                        .HasColumnType("uuid")
                        .HasColumnName("regra_id");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("tipo");

                    b.Property<Guid>("VersaoDeRegraId")
                        .HasColumnType("uuid")
                        .HasColumnName("versao_de_regra_id");

                    b.HasKey("Id")
                        .HasName("pk_sinais_de_risco");

                    b.HasIndex("AvaliacaoId")
                        .HasDatabaseName("ix_sinais_de_risco_avaliacao_id");

                    b.HasIndex("VersaoDeRegraId")
                        .HasDatabaseName("ix_sinais_de_risco_versao_de_regra_id");

                    b.ToTable("sinais_de_risco", (string)null);
                });

            modelBuilder.Entity("CentralAntifraude.Domain.Risco.VersaoDePerfilDeRisco", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("LimiarDeBloqueio")
                        .HasColumnType("integer")
                        .HasColumnName("limiar_de_bloqueio");

                    b.Property<int>("LimiarDeRevisao")
                        .HasColumnType("integer")
                        .HasColumnName("limiar_de_revisao");

                    b.Property<int>("Numero")
                        .HasColumnType("integer")
                        .HasColumnName("numero");

                    b.Property<Guid>("OrganizacaoId")
                        .HasColumnType("uuid")
                        .HasColumnName("organizacao_id");

                    b.Property<Guid>("PerfilId")
                        .HasColumnType("uuid")
                        .HasColumnName("perfil_id");

                    b.Property<DateTimeOffset>("PublicadaEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("publicada_em");

                    b.HasKey("Id")
                        .HasName("pk_versoes_de_perfil_de_risco");

                    b.HasIndex("OrganizacaoId", "PublicadaEm")
                        .HasDatabaseName("ix_versoes_de_perfil_de_risco_organizacao_id_publicada_em");

                    b.HasIndex("PerfilId", "Numero")
                        .IsUnique()
                        .HasDatabaseName("ix_versoes_de_perfil_de_risco_perfil_id_numero");

                    b.ToTable("versoes_de_perfil_de_risco", (string)null);
                });

            modelBuilder.Entity("CentralAntifraude.Domain.Risco.VersaoDeRegra", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Configuracao")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("configuracao");

                    b.Property<int>("Numero")
                        .HasColumnType("integer")
                        .HasColumnName("numero");

                    b.Property<Guid>("OrganizacaoId")
                        .HasColumnType("uuid")
                        .HasColumnName("organizacao_id");

                    b.Property<int>("Pontos")
                        .HasColumnType("integer")
                        .HasColumnName("pontos");

                    b.Property<DateTimeOffset>("PublicadaEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("publicada_em");

                    b.Property<Guid>("RegraId")
                        .HasColumnType("uuid")
                        .HasColumnName("regra_id");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("tipo");

                    b.HasKey("Id")
                        .HasName("pk_versoes_de_regra");

                    b.HasIndex("RegraId", "Numero")
                        .IsUnique()
                        .HasDatabaseName("ix_versoes_de_regra_regra_id_numero");

                    b.ToTable("versoes_de_regra", (string)null);
                });

            modelBuilder.Entity("CentralAntifraude.Domain.Transacoes.Transacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ChaveDeIdempotencia")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("chave_de_idempotencia");

                    b.Property<string>("ClienteExternoId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("cliente_externo_id");

                    b.Property<string>("FingerprintDoDispositivo")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("fingerprint_do_dispositivo");

                    b.Property<string>("FingerprintDoIp")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("fingerprint_do_ip");

                    b.Property<string>("FingerprintDoPayload")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("fingerprint_do_payload");

                    b.Property<string>("IdentificadorExterno")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("identificador_externo");

                    b.Property<Guid>("IntegracaoId")
                        .HasColumnType("uuid")
                        .HasColumnName("integracao_id");

                    b.Property<DateTimeOffset>("OcorridaEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ocorrida_em");

                    b.Property<Guid>("OrganizacaoId")
                        .HasColumnType("uuid")
                        .HasColumnName("organizacao_id");

                    b.Property<string>("PaisDeOrigem")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("pais_de_origem");

                    b.Property<DateTimeOffset>("RecebidaEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recebida_em");

                    b.Property<string>("ReferenciaDoInstrumento")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("referencia_do_instrumento");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Valor", "CentralAntifraude.Domain.Transacoes.Transacao.Valor#Dinheiro", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Moeda")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("moeda");

                            b1.Property<decimal>("Valor")
                                .HasPrecision(18, 4)
                                .HasColumnType("numeric(18,4)")
                                .HasColumnName("valor");
                        });

                    b.HasKey("Id")
                        .HasName("pk_transacoes");

                    b.HasIndex("IntegracaoId")
                        .HasDatabaseName("ix_transacoes_integracao_id");

                    b.HasIndex("OrganizacaoId", "RecebidaEm")
                        .HasDatabaseName("ix_transacoes_organizacao_id_recebida_em");

                    b.HasIndex("OrganizacaoId", "ClienteExternoId", "OcorridaEm")
                        .HasDatabaseName("ix_transacoes_organizacao_id_cliente_externo_id_ocorrida_em");

                    b.HasIndex("OrganizacaoId", "IntegracaoId", "ChaveDeIdempotencia")
                        .IsUnique()
                        .HasDatabaseName("ix_transacoes_idempotencia");

                    b.HasIndex("OrganizacaoId", "IntegracaoId", "IdentificadorExterno")
                        .IsUnique()
                        .HasDatabaseName("ix_transacoes_identificador_externo");

                    b.ToTable("transacoes", (string)null);
                });

            modelBuilder.Entity("CentralAntifraude.Infrastructure.Mensageria.MensagemDaFila", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Corpo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("corpo");

                    b.Property<DateTimeOffset>("DisponivelEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("disponivel_em");

                    b.Property<string>("Fila")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("fila");

                    b.Property<DateTimeOffset>("InseridaEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("inserida_em");

                    b.Property<int>("Recebimentos")
                        .HasColumnType("integer")
                        .HasColumnName("recebimentos");

                    b.Property<Guid?>("Recibo")
                        .HasColumnType("uuid")
                        .HasColumnName("recibo");

                    b.HasKey("Id")
                        .HasName("pk_fila_de_mensagens");

                    b.HasIndex("Recibo")
                        .IsUnique()
                        .HasDatabaseName("ix_fila_de_mensagens_recibo")
                        .HasFilter("recibo IS NOT NULL");

                    b.HasIndex("Fila", "DisponivelEm")
                        .HasDatabaseName("ix_fila_de_mensagens_fila_disponivel_em");

                    b.ToTable("fila_de_mensagens", (string)null);
                });

            modelBuilder.Entity("CentralAntifraude.Infrastructure.Mensageria.MensagemMorta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Corpo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("corpo");

                    b.Property<string>("Fila")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("fila");

                    b.Property<DateTimeOffset>("InseridaEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("inserida_em");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("motivo");

                    b.Property<DateTimeOffset>("MovidaEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("movida_em");

                    b.Property<int>("Recebimentos")
                        .HasColumnType("integer")
                        .HasColumnName("recebimentos");

                    b.HasKey("Id")
                        .HasName("pk_mensagens_mortas");

                    b.HasIndex("Fila", "MovidaEm")
                        .HasDatabaseName("ix_mensagens_mortas_fila_movida_em");

                    b.ToTable("mensagens_mortas", (string)null);
                });

            modelBuilder.Entity("VersaoDePerfilDeRiscoVersaoDeRegra", b =>
                {
                    b.Property<Guid>("VersaoDePerfilDeRiscoId")
                        .HasColumnType("uuid")
                        .HasColumnName("versao_de_perfil_de_risco_id");

                    b.Property<Guid>("VersoesDeRegraId")
                        .HasColumnType("uuid")
                        .HasColumnName("versoes_de_regra_id");

                    b.HasKey("VersaoDePerfilDeRiscoId", "VersoesDeRegraId")
                        .HasName("pk_versoes_de_perfil_regras");

                    b.HasIndex("VersoesDeRegraId")
                        .HasDatabaseName("ix_versoes_de_perfil_regras_versoes_de_regra_id");

                    b.ToTable("versoes_de_perfil_regras", (string)null);
                });

            modelBuilder.Entity("CentralAntifraude.Domain.Alertas.Alerta", b =>
                {
                    b.HasOne("CentralAntifraude.Domain.Risco.AvaliacaoDeRisco", null)
                        .WithMany()
                        .HasForeignKey("AvaliacaoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_alertas_avaliacoes_de_risco_avaliacao_id");

                    b.HasOne("CentralAntifraude.Domain.Identidade.Organizacao", null)
                        .WithMany()
                        .HasForeignKey("OrganizacaoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_alertas_organizacoes_organizacao_id");

                    b.HasOne("CentralAntifraude.Domain.Transacoes.Transacao", null)
                        .WithMany()
                        .HasForeignKey("TransacaoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_alertas_transacoes_transacao_id");
                });

            modelBuilder.Entity("CentralAntifraude.Domain.Eventos.EventoDeSaida", b =>
                {
                    b.HasOne("CentralAntifraude.Domain.Identidade.Organizacao", null)
                        .WithMany()
                        .HasForeignKey("OrganizacaoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_eventos_de_saida_organizacoes_organizacao_id");
                });

            modelBuilder.Entity("CentralAntifraude.Domain.Eventos.EventoProcessado", b =>
                {
                    b.HasOne("CentralAntifraude.Domain.Identidade.Organizacao", null)
                        .WithMany()
                        .HasForeignKey("OrganizacaoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_eventos_processados_organizacoes_organizacao_id");
                });

            modelBuilder.Entity("CentralAntifraude.Domain.Identidade.RefreshToken", b =>
                {
                    b.HasOne("CentralAntifraude.Domain.Identidade.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_refresh_tokens_usuarios_usuario_id");
                });

            modelBuilder.Entity("CentralAntifraude.Domain.Identidade.Usuario", b =>
                {
                    b.HasOne("CentralAntifraude.Domain.Identidade.Organizacao", null)
                        .WithMany()
                        .HasForeignKey("OrganizacaoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_usuarios_organizacoes_organizacao_id");
                });

            modelBuilder.Entity("CentralAntifraude.Domain.Integracoes.CredencialDeIntegracao", b =>
                {
                    b.HasOne("CentralAntifraude.Domain.Integracoes.Integracao", null)
                        .WithMany()
                        .HasForeignKey("IntegracaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_credenciais_de_integracao_integracoes_integracao_id");
                });

            modelBuilder.Entity("CentralAntifraude.Domain.Integracoes.Integracao", b =>
                {
                    b.HasOne("CentralAntifraude.Domain.Identidade.Organizacao", null)
                        .WithMany()
                        .HasForeignKey("OrganizacaoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_integracoes_organizacoes_organizacao_id");
                });

            modelBuilder.Entity("CentralAntifraude.Domain.Operacao.ResumoDiarioDeDecisoes", b =>
                {
                    b.HasOne("CentralAntifraude.Domain.Identidade.Organizacao", null)
                        .WithMany()
                        .HasForeignKey("OrganizacaoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_resumo_diario_de_decisoes_organizacoes_organizacao_id");
                });

            modelBuilder.Entity("CentralAntifraude.Domain.Risco.AvaliacaoDeRisco", b =>
                {
                    b.HasOne("CentralAntifraude.Domain.Transacoes.Transacao", null)
                        .WithMany()
                        .HasForeignKey("TransacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_avaliacoes_de_risco_transacoes_transacao_id");

                    b.HasOne("CentralAntifraude.Domain.Risco.VersaoDePerfilDeRisco", null)
                        .WithMany()
                        .HasForeignKey("VersaoDePerfilId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_avaliacoes_de_risco_versoes_de_perfil_de_risco_versao_de_pe");
                });

            modelBuilder.Entity("CentralAntifraude.Domain.Risco.PerfilDeRisco", b =>
                {
                    b.HasOne("CentralAntifraude.Domain.Identidade.Organizacao", null)
                        .WithMany()
                        .HasForeignKey("OrganizacaoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_perfis_de_risco_organizacoes_organizacao_id");
                });

            modelBuilder.Entity("CentralAntifraude.Domain.Risco.Regra", b =>
                {
                    b.HasOne("CentralAntifraude.Domain.Identidade.Organizacao", null)
                        .WithMany()
                        .HasForeignKey("OrganizacaoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_regras_organizacoes_organizacao_id");
                });

            modelBuilder.Entity("CentralAntifraude.Domain.Risco.SinalDeRisco", b =>
                {
                    b.HasOne("CentralAntifraude.Domain.Risco.AvaliacaoDeRisco", null)
                        .WithMany("Sinais")
                        .HasForeignKey("AvaliacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sinais_de_risco_avaliacoes_de_risco_avaliacao_id");

                    b.HasOne("CentralAntifraude.Domain.Risco.VersaoDeRegra", null)
                        .WithMany()
                        .HasForeignKey("VersaoDeRegraId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_sinais_de_risco_versoes_de_regra_versao_de_regra_id");
                });

            modelBuilder.Entity("CentralAntifraude.Domain.Risco.VersaoDePerfilDeRisco", b =>
                {
                    b.HasOne("CentralAntifraude.Domain.Risco.PerfilDeRisco", null)
                        .WithMany()
                        .HasForeignKey("PerfilId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_versoes_de_perfil_de_risco_perfis_de_risco_perfil_id");
                });

            modelBuilder.Entity("CentralAntifraude.Domain.Risco.VersaoDeRegra", b =>
                {
                    b.HasOne("CentralAntifraude.Domain.Risco.Regra", null)
                        .WithMany()
                        .HasForeignKey("RegraId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_versoes_de_regra_regras_regra_id");
                });

            modelBuilder.Entity("CentralAntifraude.Domain.Transacoes.Transacao", b =>
                {
                    b.HasOne("CentralAntifraude.Domain.Integracoes.Integracao", null)
                        .WithMany()
                        .HasForeignKey("IntegracaoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_transacoes_integracoes_integracao_id");
                });

            modelBuilder.Entity("VersaoDePerfilDeRiscoVersaoDeRegra", b =>
                {
                    b.HasOne("CentralAntifraude.Domain.Risco.VersaoDePerfilDeRisco", null)
                        .WithMany()
                        .HasForeignKey("VersaoDePerfilDeRiscoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_versoes_de_perfil_regras_versoes_de_perfil_de_risco_versao_");

                    b.HasOne("CentralAntifraude.Domain.Risco.VersaoDeRegra", null)
                        .WithMany()
                        .HasForeignKey("VersoesDeRegraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_versoes_de_perfil_regras_versoes_de_regra_versoes_de_regra_");
                });

            modelBuilder.Entity("CentralAntifraude.Domain.Risco.AvaliacaoDeRisco", b =>
                {
                    b.Navigation("Sinais");
                });
#pragma warning restore 612, 618
        }
    }
}
