// <auto-generated />
using System;
using CentralAntifraude.Infrastructure.Persistencia;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CentralAntifraude.Infrastructure.Persistencia.Migrations
{
    [DbContext(typeof(CentralAntifraudeDbContext))]
    [Migration("20260903233026_IdentidadeEMultiTenancy")]
    partial class IdentidadeEMultiTenancy
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CentralAntifraude.Domain.Auditoria.RegistroDeAuditoria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AutorDescricao")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("autor_descricao");

                    b.Property<Guid?>("AutorId")
                        .HasColumnType("uuid")
                        .HasColumnName("autor_id");

                    b.Property<string>("Detalhe")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("detalhe");

                    b.Property<string>("Entidade")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("entidade");

                    b.Property<string>("EntidadeId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("entidade_id");

                    b.Property<string>("IdDeCorrelacao")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("id_de_correlacao");

                    b.Property<DateTimeOffset>("OcorridoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ocorrido_em");

                    b.Property<string>("Operacao")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("operacao");

                    b.Property<Guid>("OrganizacaoId")
                        .HasColumnType("uuid")
                        .HasColumnName("organizacao_id");

                    b.HasKey("Id")
                        .HasName("pk_registros_de_auditoria");

                    b.HasIndex("OrganizacaoId", "OcorridoEm")
                        .HasDatabaseName("ix_registros_de_auditoria_organizacao_id_ocorrido_em");

                    b.ToTable("registros_de_auditoria", (string)null);
                });

            modelBuilder.Entity("CentralAntifraude.Domain.Identidade.Organizacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativa")
                        .HasColumnType("boolean")
                        .HasColumnName("ativa");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("codigo");

                    b.Property<DateTimeOffset>("CriadaEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criada_em");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome");

                    b.HasKey("Id")
                        .HasName("pk_organizacoes");

                    b.HasIndex("Codigo")
                        .IsUnique()
                        .HasDatabaseName("ix_organizacoes_codigo");

                    b.ToTable("organizacoes", (string)null);
                });

            modelBuilder.Entity("CentralAntifraude.Domain.Identidade.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<DateTimeOffset>("ExpiraEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expira_em");

                    b.Property<Guid>("FamiliaId")
                        .HasColumnType("uuid")
                        .HasColumnName("familia_id");

                    b.Property<string>("HashDoToken")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("hash_do_token");

                    b.Property<string>("MotivoDaRevogacao")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("motivo_da_revogacao");

                    b.Property<Guid>("OrganizacaoId")
                        .HasColumnType("uuid")
                        .HasColumnName("organizacao_id");

                    b.Property<DateTimeOffset?>("RevogadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revogado_em");

                    b.Property<DateTimeOffset?>("UsadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("usado_em");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id")
                        .HasName("pk_refresh_tokens");

                    b.HasIndex("FamiliaId")
                        .HasDatabaseName("ix_refresh_tokens_familia_id");

                    b.HasIndex("HashDoToken")
                        .IsUnique()
                        .HasDatabaseName("ix_refresh_tokens_hash_do_token");

                    b.HasIndex("UsuarioId")
                        .HasDatabaseName("ix_refresh_tokens_usuario_id");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("CentralAntifraude.Domain.Identidade.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<DateTimeOffset>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("email");

                    b.Property<string>("HashDaSenha")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("hash_da_senha");

                    b.Property<string>("NomeCompleto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome_completo");

                    b.Property<Guid>("OrganizacaoId")
                        .HasColumnType("uuid")
                        .HasColumnName("organizacao_id");

                    b.Property<string>("Perfil")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("perfil");

                    b.HasKey("Id")
                        .HasName("pk_usuarios");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_usuarios_email");

                    b.HasIndex("OrganizacaoId", "NomeCompleto")
                        .HasDatabaseName("ix_usuarios_organizacao_id_nome_completo");

                    b.ToTable("usuarios", (string)null);
                });

            modelBuilder.Entity("CentralAntifraude.Domain.Identidade.RefreshToken", b =>
                {
                    b.HasOne("CentralAntifraude.Domain.Identidade.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_refresh_tokens_usuarios_usuario_id");
                });

            modelBuilder.Entity("CentralAntifraude.Domain.Identidade.Usuario", b =>
                {
                    b.HasOne("CentralAntifraude.Domain.Identidade.Organizacao", null)
                        .WithMany()
                        .HasForeignKey("OrganizacaoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_usuarios_organizacoes_organizacao_id");
                });
#pragma warning restore 612, 618
        }
    }
}
