<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>CentralAntifraude.ArchitectureTests</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\CentralAntifraude.Api\CentralAntifraude.Api.csproj" />
    <ProjectReference Include="..\..\src\CentralAntifraude.Application\CentralAntifraude.Application.csproj" />
    <ProjectReference Include="..\..\src\CentralAntifraude.Domain\CentralAntifraude.Domain.csproj" />
    <ProjectReference Include="..\..\src\CentralAntifraude.Infrastructure\CentralAntifraude.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit.v3" />
    <PackageReference Include="xunit.runner.visualstudio" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

</Project>
